[pytest]
markers =
    smoke: fast, critical tests
    full: complete test suite
    negative: negative scenarios
    post: post scenarios
    album: album scenarios
    user: user scenarios

log_cli = true
log_cli_level = INFO

retries = 3
retry_delay = 1

addopts = --html=reports/html_report.html --self-contained-html --alluredir=reports/allure-results